### PR TITLE
CircuitBreaker + Predicate + Failure interaction.

### PR DESCRIPTION
**Pull request by htmldoug**
Hi @jhalterman! I've been pushing failsafe at Rally Health as a superior replacement to our lesser in-house version. I'm a big fan of this project and grateful that it exists.

@KyohoSatsumi and I encountered some surprising behavior involving `CircuitBreaker.failIf(Predicate)` when an operation fails (with a `Throwable`) and the `Predicate` is still invoked with a `null` argument. In the worst case, the operation is never completed!

I've created a couple minimal failing test cases illustrating my expectations and some comments around the parts of the implementation that I think might be problematic. Hoping to get your feedback around the original intent and proposed solution.

### CODE REVIEW

**Comment by htmldoug** [comment]
I went ahead and added fixes.
If they look good to you, I'll strip out the uncertainty in the comments and summarize.

**Comment by htmldoug** [comment]
I've removed the temporary discussion javadoc and summarized. This should be ready to merge now as is.

@jhalterman please review when you get a sec and let me know if you'd like for me to make any changes.

**Comment by usufruct99** [comment]
Would love to be able to start using this in our projects! Attention appreciated. :)

**Comment by jhalterman** [comment]
Thanks for this PR.

Ignoring user-land exceptions inside of predicates is a good idea to me. We actually have 2 more places where predicates are used, in RetryPolicies. Care to ignore them there as well?

https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicy.java#L223
https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicy.java#L241

Other than that, the PR looks good. 👍

**Comment by htmldoug** [comment]
You bet. Done.

**Comment by jhalterman** [comment]
Nice - thanks for this!

**Comment by laflechejonathan** [comment]
@jhalterman, any plans to cut a release with this fix?

**Comment by jhalterman** [comment]
@laflechejonathan Sure - apologies. I've had some work pending for a while that I was waiting on, but no need to wait just for this fix.

Just cut 1.1.1 release. Should be in central shortly.

**Pull request merged**
